plugins {
    id 'org.sonarqube' version '7.3.1.8318'
}

sonar {
    properties {
        property 'sonar.projectKey', 'ivakk_fitrack'
        property 'sonar.organization', 'ivakk'
        property 'sonar.host.url', System.getenv('SONAR_HOST_URL') ?: 'https://sonarcloud.io'
    }
}

tasks.register('build') {
    dependsOn subprojects.collect { "${it.path}:build" }
}

tasks.named('sonar') {
    dependsOn 'build'
}
