spring.profiles.active=dev

spring.data.mongodb.auto-index-creation=true

server.port=8080

security.jwt.secret=supersecretkeysupersecretkey123456
security.jwt.issuer=fitrack-iam
security.jwt.access-ttl-minutes=60

security.password.bcrypt-strength=12
security.password.pepper=fitrackPepperValue

cors.allowed-origins=http://localhost:5173,http://localhost,http://127.0.0.1
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Content-Type
cors.allow-credentials=true

management.endpoints.web.exposure.include=health,info

# RabbitMQ (domain events)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=fitrack
spring.rabbitmq.password=fitrack
fitrack.messaging.exchange=fitrack.events
fitrack.messaging.routing-keys.user-registered=user.registered
fitrack.messaging.routing-keys.user-deleted=user.deleted

logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
