spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/fitrack_iam}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:fitrack}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:fitrack}
