# zap-baseline rule configuration file — tab-separated columns (ID, level, description)
# Change WARN to IGNORE to ignore rule or FAIL to fail if rule matches

10049	IGNORE	(Storable and Cacheable Content)
10116	IGNORE	(ZAP is Out of Date)
