apiVersion: v1
kind: Secret
metadata:
  name: fitrack-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fitrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  jwt-issuer: {{ .Values.secrets.jwtIssuer | quote }}
  gateway-trusted-secret: {{ .Values.secrets.gatewayTrustedSecret | quote }}
  workout-encryption-key: {{ .Values.secrets.workoutEncryptionKey | quote }}
  rabbitmq-user: {{ .Values.secrets.rabbitmqUser | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | quote }}
